package blanco.sfdc.jdbc.driver.simple;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import blanco.sfdc.jdbc.driver.BlancoSfdcJdbcConnection;

public abstract class BlancoSfdcJdbcSimpleStatement implements Statement {
	protected BlancoSfdcJdbcConnection conn = null;

	protected boolean isClosed = false;

	public BlancoSfdcJdbcSimpleStatement(final BlancoSfdcJdbcConnection conn) {
		this.conn = conn;
	}

	public void close() throws SQLException {
		isClosed = true;
	}

	public boolean isClosed() throws SQLException {
		return isClosed;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int executeUpdate(String sql) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getMaxFieldSize() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setMaxFieldSize(int max) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getMaxRows() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setMaxRows(int max) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setEscapeProcessing(boolean enable) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getQueryTimeout() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setQueryTimeout(int seconds) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void cancel() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public SQLWarning getWarnings() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void clearWarnings() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setCursorName(String name) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean execute(String sql) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public ResultSet getResultSet() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getUpdateCount() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean getMoreResults() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setFetchDirection(int direction) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getFetchDirection() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setFetchSize(int rows) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getFetchSize() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getResultSetConcurrency() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getResultSetType() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void addBatch(String sql) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void clearBatch() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int[] executeBatch() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public Connection getConnection() throws SQLException {
		return conn;
	}

	public boolean getMoreResults(int current) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public ResultSet getGeneratedKeys() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean execute(String sql, String[] columnNames) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public int getResultSetHoldability() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public void setPoolable(boolean poolable) throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean isPoolable() throws SQLException {
		return false;
	}

	public void closeOnCompletion() throws SQLException {
		throw new SQLException("Not Implemented.");
	}

	public boolean isCloseOnCompletion() throws SQLException {
		throw new SQLException("Not Implemented.");
	}
}
